- uses: actions/checkout@v2
- uses: ruby/setup-ruby@v1
  with:
    ruby-version: '3.0'
    bundler-cache: true
    working-directory: 'ios'
- uses: maierj/fastlane-action@v3.0.0
  with:
    lane: 'beta'
    subdirectory: 'ios'
